### ISSUE TITLE
PlayListConfig Don't work

### ISSUE THREAD

**Issue by TCGiSOLux** [xan1242/XNFSMusicPlayer#10]
Hello. I Installed XNFSMusicPlayer, when i changed soundtracks in NFS MW Netshow Challenges mod playlist config is broken. Please fix it playlist config to work! Thanks.

**Comment by xan1242** [comment]
I need more information to figure out what's wrong exactly.

I need a couple things:

1. Your actual playlist and playlistconfig files
2. Which song number is it exactly?

If it's for a song that's at position higher than 32, then [this is a known issue](https://github.com/xan1242/XNFSMusicPlayer/issues/5).

**Comment by TCGiSOLux** [comment]
I installed the XNFS Music Player script into my game yesterday, but it installed fine and the Playlist Config ini file doesn't work.

**Comment by xan1242** [comment]
As I said before, please attach your PlaylistConfig.ini and Playlist here so I can figure out what's wrong.

**Comment by xan1242** [comment]
@YlayaQueen Can you please respond to the last question? If not, I'm going to close the issue in 3 days.

**Comment by xan1242** [comment]
Didn't track this so I'm late, but I'm closing the issue now due to lack of information.

If you need help again, please re-open the issue.
