### ISSUE TITLE
I have a issue with the ingame music option

### ISSUE THREAD

**Issue by boristhething** [xan1242/XNFSMusicPlayer#12]
For example i select certain songs to play at the menu and the other during races, but doesn't work very well. Sometimes it will play the menu song during races and the race song will play in the menu. Did i missed something in the config or is it a bug?

**Comment by alexpado** [comment]
How many songs do you have in your playlist ? This might be related to #5

**Comment by boristhething** [comment]
i have like 30 songs

**Comment by xan1242** [comment]
Repeat of https://github.com/xan1242/XNFSMusicPlayer/issues/5
