### ISSUE TITLE
Out of memory in pool Main Pool (null)

### ISSUE THREAD

**Issue by Clavietika** [xan1242/XNFSMusicPlayer#2]
![dsfsdgfsadgsdgfs](https://user-images.githubusercontent.com/40206185/148973224-03991996-27f6-4f8c-a84b-1249ed4b35b3.png)
The game crashes and then shows this error after I put my playlist file, 79 songs all mp3 and renamed with simple names. Newest version crashes too but this one shows me the error.

**Comment by xan1242** [comment]
If you need help, open a new issue. Sorry for not helping in time.
