### ISSUE TITLE
Error running in Xnfs Music Player

### ISSUE THREAD

**Issue by BrankoGames44** [xan1242/XNFSMusicPlayer#9]
When running Xnfs Music Player program, unable to load files: ConsoleAttachment.asi, XNFSMusicPlayer.asi, XNFSMusicPlayerInstaller.asi for Windows 10 Pro.

**Comment by xan1242** [comment]
I'm going to need more information than this.

These files are in the scripts folder and are automatically loaded by the ASI loader, so you don't load them yourself by hand.

Are you getting an error message and that's what it says?

**Comment by BrankoGames44** [comment]
I only have this error information. These are errors when I run NEED FOR SPEED MOST WANTED 2005.

**Comment by xan1242** [comment]
Can't you provide a screenshot? Anything at all?

If you can't, I can't help you either.

Install VS2022 redistributable and follow the installation instructions, that's all I can tell you.

**Comment by BrankoGames44** [comment]
Wait a moment and I'll take a screenshot.

**Comment by BrankoGames44** [comment]
See attached screenshots.
![Console](https://user-images.githubusercontent.com/115380471/194732888-5197ebaf-f1f2-4ed2-b543-80e1e30bf876.PNG)
![XNFSMUSICPLAYER ASI](https://user-images.githubusercontent.com/115380471/194732889-0f4b0e56-abbc-45fd-9e0b-9fd5c71d9936.PNG)
![XNFSMUSICPLAYERINSTALLER ASI](https://user-images.githubusercontent.com/115380471/194732890-63cbc735-41d0-430c-94ec-2e51bbc5c32f.PNG)

**Comment by xan1242** [comment]
```
126 (0x7E)

The specified module could not be found.
```

This could mean a lot of things, but most probably, since not even the console window ASI loads, you're missing VC redistributables.

Install this: https://aka.ms/vs/17/release/vc_redist.x86.exe

If it still doesn't run, try running the game as administrator and see if that fixes it.

**Comment by BrankoGames44** [comment]
OK. I am going to try.

**Comment by BrankoGames44** [comment]
It worked out! Thank you for your help. I'm Branko. I live in Brazil. It was really worth it. God bless you!

**Comment by xan1242** [comment]
No problem, glad to see it solved!

Closing...
